apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deploy
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: g3.skb:8500/dev-pipeline/node
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"    
        ports:
        - containerPort: 3000
          name: apport
        livenessProbe:
          httpGet:
            path: /health
            port: apport
          initialDelaySeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: apport
          initialDelaySeconds: 1
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: node-svc
spec:
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 3000
      targetPort: apport
